//! Phase 12 (plan Phase E.2) — sharded + union streaming for the new formats.
//!
//! Sharded mode (`stream_quantize_sharded`) processes each input shard as its
//! own self-contained file (own calibration cache, own manifest, own
//! per-shard `__metadata__`). Byte-parity for the new formats is defined
//! against ctq's whole-file path run INDEPENDENTLY on each committed input
//! shard — the per-shard goldens under
//! `tests/golden/sharded_model/output_sharded_<fmt>/` (generated by
//! `tools/gen_golden_sharded_formats.py`, CUDA hidden, seed 233983427).
//!
//! Cross-shard bias semantics (mirrors the reference): in SHARDED mode a bias
//! whose weight lives in another shard copies unchanged (each shard is
//! independent); in UNION/single mode the bias is corrected across shards. The
//! two legitimately differ on `blocks.1.bias` — this file tests SHARDED mode
//! against the per-shard goldens, which encode the independent-shard behavior.

mod common;

use common::{assert_metadata_parity, assert_payload_parity, golden};
use quant_core::discover::discover_shards;
use quant_core::manifest::{Format, QuantConfig, ScalingMode};
use quant_core::stream::stream_quantize_sharded;

const SHARDS: [&str; 3] = [
    "model-00001-of-00003.safetensors",
    "model-00002-of-00003.safetensors",
    "model-00003-of-00003.safetensors",
];

fn family_b_config(format: Format) -> QuantConfig {
    let (target, block_size) = match format {
        Format::Mxfp8 => ("mxfp8", 32),
        Format::Nvfp4 => ("nvfp4", 16),
        _ => unreachable!(),
    };
    QuantConfig {
        format,
        target_format: target.into(),
        int8: false,
        scaling_mode: ScalingMode::Block,
        block_size,
        ..QuantConfig::default()
    }
}

/// Run sharded streaming for `format` and assert, per shard, payload parity +
/// `__metadata__` parity against the per-shard ctq golden
/// (`output_sharded_<suffix>/<shard>`), plus the global manifest + copied
/// index/sidecars.
fn run_sharded_parity(format: Format, golden_suffix: &str) {
    let input_dir = golden("sharded_model/input");
    let model = discover_shards(&input_dir).expect("discover sharded fixture");
    assert_eq!(model.shard_files, SHARDS.to_vec());

    let tmp = tempfile::tempdir().unwrap();
    let out_dir = tmp.path().join("out");
    let config = family_b_config(format);

    let result =
        stream_quantize_sharded(&model, &out_dir, &config).expect("sharded streaming must succeed");
    assert_eq!(result.shards.len(), SHARDS.len());

    // Per-shard payload + metadata parity vs the per-shard ctq golden.
    for shard in &SHARDS {
        let ours = out_dir.join(shard);
        let gold = golden(&format!(
            "sharded_model/output_sharded_{golden_suffix}/{shard}"
        ));
        assert_payload_parity(&ours, &gold, &format!("{shard}/{golden_suffix} sharded"));
        assert_metadata_parity(
            &ours,
            &gold,
            &format!("{shard}/{golden_suffix} sharded metadata"),
        );
    }

    // Index json + sidecars copied verbatim; global manifest written.
    assert!(out_dir.join("model.safetensors.index.json").is_file());
    assert!(out_dir.join(".quant-manifest.json").is_file());
    assert!(out_dir.join("config.json").is_file());
}

#[test]
fn mxfp8_sharded_smoke_and_per_shard_payload_parity() {
    run_sharded_parity(Format::Mxfp8, "mxfp8");
}

#[test]
fn nvfp4_sharded_smoke_and_per_shard_payload_parity() {
    run_sharded_parity(Format::Nvfp4, "nvfp4");
}

/// FP8 block scaling through sharded mode, per-shard parity vs the per-shard
/// ctq golden (`output_sharded_fp8`).
#[test]
fn fp8_sharded_per_shard_payload_parity() {
    let input_dir = golden("sharded_model/input");
    let model = discover_shards(&input_dir).expect("discover sharded fixture");

    let tmp = tempfile::tempdir().unwrap();
    let out_dir = tmp.path().join("out");
    let config = QuantConfig {
        format: Format::Fp8E4m3,
        target_format: "fp8".into(),
        int8: false,
        scaling_mode: ScalingMode::Block,
        block_size: 128,
        ..QuantConfig::default()
    };

    stream_quantize_sharded(&model, &out_dir, &config).expect("sharded fp8 must succeed");

    for shard in &SHARDS {
        let ours = out_dir.join(shard);
        let gold = golden(&format!("sharded_model/output_sharded_fp8/{shard}"));
        assert_payload_parity(&ours, &gold, &format!("{shard}/fp8 sharded"));
        // FP8 outputs carry no __metadata__ (plan §3.3).
        common::assert_no_metadata(&ours, &format!("{shard}/fp8 sharded"));
    }
}

// --------------------------------------------------------------------------- //
// Union / single mode (all shards -> ONE output file)
// --------------------------------------------------------------------------- //

/// Union streaming of the sharded fixture with FP8: no byte golden exists for
/// the merged output (ctq is whole-file-only and the reference streaming path
/// is INT8-only), so the gate is structural validity (validator passes,
/// incl. numeric) + double-run determinism. Cross-shard bias correction is
/// exercised here (`blocks.1.bias` in shard2, `blocks.1.weight` in shard3).
#[test]
fn fp8_union_single_mode_structural_and_deterministic() {
    use quant_core::stream::stream_quantize_shards;
    use quant_core::validator::validate_comfy_quant;

    let input_dir = golden("sharded_model/input");
    let shards: Vec<std::path::PathBuf> = SHARDS.iter().map(|s| input_dir.join(s)).collect();
    let config = QuantConfig {
        format: Format::Fp8E4m3,
        target_format: "fp8".into(),
        int8: false,
        scaling_mode: ScalingMode::Block,
        block_size: 128,
        ..QuantConfig::default()
    };

    let tmp = tempfile::tempdir().unwrap();
    let out1 = tmp.path().join("union1.safetensors");
    let out2 = tmp.path().join("union2.safetensors");

    stream_quantize_shards(&shards, &out1, &config).expect("union streaming must succeed");
    stream_quantize_shards(&shards, &out2, &config).expect("union streaming (2nd) must succeed");

    // Determinism: two fresh union runs are byte-identical.
    assert_eq!(
        std::fs::read(&out1).unwrap(),
        std::fs::read(&out2).unwrap(),
        "two fresh FP8 union runs must be byte-identical"
    );

    // Structural validity (header + numeric pass).
    let report = validate_comfy_quant(&out1, true);
    assert!(
        report.ok,
        "union FP8 output must validate (incl. numeric): {:?}",
        report
    );

    // The cross-shard bias must be present and corrected (F32 [128]).
    let r = common::load(&out1);
    let bias = r
        .header()
        .get("blocks.1.bias")
        .expect("union output must carry blocks.1.bias");
    assert_eq!(bias.dtype_raw, "F32");
    assert_eq!(bias.shape, vec![128]);
}

// --------------------------------------------------------------------------- //
// E.5 — calibration draw-order lock
// --------------------------------------------------------------------------- //
//
// The committed `sharded_model` fixture cannot lock down `CalibOrder`: within
// every shard its 2D `.weight` names happen to be alphabetical, so file order
// == sorted order and both draw strategies produce identical RNG streams.
//
// `tests/golden/sharded_unsorted` (generated by
// `tools/gen_golden_sharded_unsorted.py`, CUDA hidden, seed 233983427) closes
// that gap. Its shards are written with a HAND-BUILT safetensors header —
// `safetensors.torch.save_file` groups keys by dtype and sorts alphabetically
// within each group (see `tools/probe_st_order.py`), so it can never emit a
// non-alphabetical within-dtype order. Shard 1 therefore lists
// `zzz.weight` (in_features=256) BEFORE `aaa.weight` (=128):
//
//     file order of 2D weights : [zzz.weight(256), aaa.weight(128)]
//     sorted-by-name order     : [aaa.weight(128), zzz.weight(256)]
//
// Reference behavior, confirmed at source:
//   * INT8 — the quantui REFERENCE streaming quantizer
//     (the reference stream_quant.py) reads the header RAW
//     (`_resolve_union_header` -> `read_safetensors_header`) and walks `names`
//     in on-disk order.                                 -> FileOrderAll2D
//   * FP8 / MXFP8 / NVFP4 — ctq. Every ctq entry point builds its key list
//     from `MemoryEfficientSafeOpen`, which in the default (non-low-memory)
//     mode does `list(safe_open(...).keys())`. `safe_open.keys()` returns the
//     names SORTED ALPHABETICALLY, never in file order — verified
//     deterministic by `tools/probe_safe_open_keys.py`. FP8 then iterates that
//     sorted list (`fp8_conversion.py:304`); MXFP8/NVFP4 pre-filter and
//     `sorted()` it (`{mxfp8,nvfp4}_conversion.py:193`). Same result.
//                                                       -> SortedWeightsOnly
//
// So the split is NOT "INT8+FP8 vs MXFP8+NVFP4" — it is "reference streaming
// (INT8) vs ctq (everything else)". Generating BOTH sides against the SAME
// discriminating fixture is what makes this a real lock: a port that
// collapsed the two orders into one mismatches at least one golden, in
// either direction. (This is exactly the bug E.5 caught — FP8 was previously
// classified as file order, and passed every pre-existing fixture because
// `save_file` writes same-dtype 2D weights alphabetically.)

const UNSORTED_SHARDS: [&str; 2] = [
    "model-00001-of-00002.safetensors",
    "model-00002-of-00002.safetensors",
];

/// ctq parity seed — the streaming path's `calib_seed` default.
const CALIB_SEED: i64 = 233_983_427;

fn unsorted_config(format: Format) -> QuantConfig {
    match format {
        // The INT8 goldens come from the reference streaming quantizer, whose
        // config is exactly `QuantConfig::default()` (int8 / block / 128 /
        // simple / heur / bfloat16).
        Format::Int8 => QuantConfig::default(),
        _ => {
            let (target, block_size) = match format {
                Format::Fp8E4m3 => ("fp8", 128),
                Format::Mxfp8 => ("mxfp8", 32),
                Format::Nvfp4 => ("nvfp4", 16),
                Format::Int8 => unreachable!(),
            };
            QuantConfig {
                format,
                target_format: target.into(),
                int8: false,
                scaling_mode: ScalingMode::Block,
                block_size,
                ..QuantConfig::default()
            }
        }
    }
}

/// Guard against the fixture silently regressing into a NON-discriminating one
/// (e.g. if it is ever regenerated with `save_file`, which would sort the
/// keys). Shard 1 must keep its 2D weights in non-alphabetical file order.
#[test]
fn unsorted_fixture_is_discriminating() {
    let input_dir = golden("sharded_unsorted/input");
    let shard1 = input_dir.join(UNSORTED_SHARDS[0]);

    let r = common::load(&shard1);
    let file_order: Vec<&str> = r
        .header()
        .names()
        .filter(|n| n.ends_with(".weight"))
        .map(|n| n.as_str())
        .collect();
    let sorted: Vec<&str> = {
        let mut s = file_order.clone();
        s.sort_unstable();
        s
    };
    assert_ne!(
        file_order, sorted,
        "E.5 fixture no longer discriminates: shard 1's 2D weights are in \
         alphabetical file order {file_order:?}. Regenerate with \
         tools/gen_golden_sharded_unsorted.py (hand-built header)."
    );

    // And the two draw orders must actually produce DIFFERENT calibration
    // streams, otherwise the E2E tests below prove nothing about ordering.
    let pairs: Vec<(String, Option<usize>)> = {
        let mut v = Vec::new();
        for n in r.header().names() {
            let info = r.header().get(n).unwrap();
            let n2d =
                (n.ends_with(".weight") && info.shape.len() == 2).then(|| info.shape[1] as usize);
            v.push((n.clone(), n2d));
        }
        v
    };

    use quant_core::bias_correction::CalibCache;
    use quant_core::manifest::CalibOrder;

    let by_file = CalibCache::build(
        pairs.iter().cloned(),
        CalibOrder::FileOrderAll2D,
        CALIB_SEED as u64,
    );
    let by_sorted = CalibCache::build(
        pairs.iter().cloned(),
        CalibOrder::SortedWeightsOnly,
        CALIB_SEED as u64,
    );

    let mut diverged = 0usize;
    for n in [256usize, 128usize] {
        let a = by_file
            .get(n)
            .unwrap_or_else(|| panic!("file-order cache must cover in_features {n}"));
        let b = by_sorted
            .get(n)
            .unwrap_or_else(|| panic!("sorted-order cache must cover in_features {n}"));
        if a != b {
            diverged += 1;
        }
    }
    assert_eq!(
        diverged, 2,
        "E.5 fixture does not discriminate the calibration streams: the two \
         draw orders produced identical calib data for in_features 256/128 \
         (got {diverged}/2 differing). The E2E tests below would then be a \
         no-op for ordering."
    );
}

/// Sharded streaming over the unsorted fixture: per-shard payload parity vs
/// the per-shard golden, which encodes that family's draw order.
fn run_unsorted_parity(format: Format, golden_suffix: &str) {
    let input_dir = golden("sharded_unsorted/input");
    let model = discover_shards(&input_dir).expect("discover unsorted fixture");
    assert_eq!(model.shard_files, UNSORTED_SHARDS.to_vec());

    let tmp = tempfile::tempdir().unwrap();
    let out_dir = tmp.path().join("out");
    let config = unsorted_config(format);

    let result =
        stream_quantize_sharded(&model, &out_dir, &config).expect("sharded streaming must succeed");
    assert_eq!(result.shards.len(), UNSORTED_SHARDS.len());

    for shard in &UNSORTED_SHARDS {
        let ours = out_dir.join(shard);
        let gold = golden(&format!(
            "sharded_unsorted/output_sharded_{golden_suffix}/{shard}"
        ));
        assert_payload_parity(&ours, &gold, &format!("{shard}/{golden_suffix} unsorted"));

        // Metadata policy (plan §3.3): family B carries
        // `_quantization_metadata`, FP8 never does.
        if matches!(format, Format::Mxfp8 | Format::Nvfp4) {
            assert_metadata_parity(
                &ours,
                &gold,
                &format!("{shard}/{golden_suffix} unsorted metadata"),
            );
        } else {
            common::assert_no_metadata(&ours, &format!("{shard}/{golden_suffix} unsorted"));
        }
    }
}

/// INT8 draws in FILE order — the reference streaming quantizer reads the
/// header raw (`_resolve_union_header` -> `read_safetensors_header`), so it
/// sees shard 1 as `zzz.weight(256)` then `aaa.weight(128)`. This is the
/// anchor that stops anyone unifying the two orders in the wrong direction.
#[test]
fn int8_unsorted_sharded_calib_order_parity() {
    run_unsorted_parity(Format::Int8, "int8");
}

/// FP8 draws in SORTED order: ctq's key list comes from `safe_open.keys()`,
/// which is always alphabetical, so it sees `aaa.weight(128)` first.
#[test]
fn fp8_unsorted_sharded_calib_order_parity() {
    run_unsorted_parity(Format::Fp8E4m3, "fp8");
}

/// MXFP8 draws over `sorted(2D weights)` — `aaa.weight(128)` then
/// `zzz.weight(256)`, i.e. the OPPOSITE of the INT8 golden above. Both pass
/// against the same fixture, so a single shared draw order cannot satisfy
/// both, whichever way it is collapsed.
#[test]
fn mxfp8_unsorted_sharded_calib_order_parity() {
    run_unsorted_parity(Format::Mxfp8, "mxfp8");
}

#[test]
fn nvfp4_unsorted_sharded_calib_order_parity() {
    run_unsorted_parity(Format::Nvfp4, "nvfp4");
}
