//! Phase 6 E2E tests: sharded input/output byte-parity vs Python goldens.
//!
//! Fixture (e): `tests/golden/sharded_model/` — a 3-shard synthetic HF model
//! generated by `tools/gen_golden_sharded.py` with the reference streaming
//! quantizer (CUDA hidden → eager/CPU path). Parity traps exercised:
//! - `aaa_skipped.weight` [128,192] is SKIPPED but sorts first: the calib
//!   cache must draw RNG for it (in_features=192) before the quantized
//!   weights, or bias correction diverges.
//! - `blocks.1.bias` (shard2) has its weight in shard3: single mode corrects
//!   it across shards; sharded mode copies it unchanged. The two output modes
//!   therefore legitimately differ on that tensor.
//! - `small.weight` [128,64] is skipped and cast to the output dtype (bf16).
//!
//! Single mode  = `stream_quantize_shards` (union → one file).
//! Sharded mode = `stream_quantize_sharded` (one output shard per input shard
//! + index/sidecars copied + global `.quant-manifest.json`).

use std::path::PathBuf;

use quant_core::discover::discover_shards;
use quant_core::manifest::QuantConfig;
use quant_core::stream::{stream_quantize_sharded, stream_quantize_shards, SHARDED_MANIFEST_NAME};

fn golden(name: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.pop();
    p.join("tests/golden").join(name)
}

fn ref_config() -> QuantConfig {
    QuantConfig::default()
}

fn files_equal(a: &std::path::Path, b: &std::path::Path) -> bool {
    if std::fs::metadata(a).unwrap().len() != std::fs::metadata(b).unwrap().len() {
        return false;
    }
    std::fs::read(a).unwrap() == std::fs::read(b).unwrap()
}

const SHARDS: [&str; 3] = [
    "model-00001-of-00003.safetensors",
    "model-00002-of-00003.safetensors",
    "model-00003-of-00003.safetensors",
];

#[test]
fn discover_golden_sharded_model() {
    let input = golden("sharded_model").join("input");
    let model = discover_shards(&input).unwrap();
    assert_eq!(model.shard_files, SHARDS);
    assert_eq!(model.non_weight_files, vec!["config.json"]);
    assert_eq!(model.weight_map["blocks.0.weight"], SHARDS[0]);
    assert_eq!(model.weight_map["blocks.1.bias"], SHARDS[1]);
    assert_eq!(model.weight_map["blocks.1.weight"], SHARDS[2]);
    assert_eq!(model.shard_paths().len(), 3);
}

#[test]
fn e2e_sharded_single_mode_byte_parity() {
    let dir = golden("sharded_model");
    let input = dir.join("input");
    let model = discover_shards(&input).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("output_single.safetensors");

    let result = stream_quantize_shards(&model.shard_paths(), &out, &ref_config()).unwrap();

    assert!(
        files_equal(&out, &dir.join("output_single.safetensors")),
        "union-streamed single output must be byte-identical to the golden"
    );

    // Per-run manifest: byte-identical (path-independent fields only).
    let our_manifest = out.with_extension("safetensors.quant-manifest.json");
    assert!(
        files_equal(
            &our_manifest,
            &dir.join("output_single.safetensors.quant-manifest.json")
        ),
        "single-mode manifest must be byte-identical to the golden"
    );
    assert_eq!(result.config_hash, "56920c6553cfa241");
    assert_eq!(result.done.len(), 9);
}

#[test]
fn e2e_sharded_output_mode_byte_parity() {
    let dir = golden("sharded_model");
    let input = dir.join("input");
    let model = discover_shards(&input).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let out_dir = tmp.path().join("output_sharded");

    let result = stream_quantize_sharded(&model, &out_dir, &ref_config()).unwrap();

    // Every output shard byte-identical.
    for shard in &SHARDS {
        assert!(
            files_equal(
                &out_dir.join(shard),
                &dir.join("output_sharded").join(shard)
            ),
            "output shard {shard} must be byte-identical to the golden"
        );
        // Per-shard manifests are path-independent → byte-identical too.
        assert!(
            files_equal(
                &out_dir.join(format!("{shard}.quant-manifest.json")),
                &dir.join("output_sharded")
                    .join(format!("{shard}.quant-manifest.json"))
            ),
            "per-shard manifest for {shard} must be byte-identical"
        );
    }

    // Index json + sidecars copied verbatim.
    assert!(files_equal(
        &out_dir.join("model.safetensors.index.json"),
        &input.join("model.safetensors.index.json")
    ));
    assert!(files_equal(
        &out_dir.join("config.json"),
        &input.join("config.json")
    ));

    // Global manifest: output_dir is path-dependent → semantic comparison.
    let ours: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(out_dir.join(SHARDED_MANIFEST_NAME)).unwrap(),
    )
    .unwrap();
    let theirs: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join("output_sharded").join(SHARDED_MANIFEST_NAME)).unwrap(),
    )
    .unwrap();
    assert_eq!(ours["version"], theirs["version"]);
    assert_eq!(ours["config_hash"], theirs["config_hash"]);
    assert_eq!(ours["shards"], theirs["shards"]);
    assert_eq!(result.config_hash, "56920c6553cfa241");
    assert_eq!(result.shards.len(), 3);
}

#[test]
fn cross_shard_bias_legitimately_diverges_between_modes() {
    // blocks.1.bias lives in shard2, its weight in shard3. Single (union)
    // mode reaches the bias before its weight across shards → corrected.
    // Sharded mode processes each shard alone → bias copied unchanged.
    let dir = golden("sharded_model");
    let single = dir.join("output_single.safetensors");
    let sharded = dir.join("output_sharded").join(SHARDS[1]);

    let read = |p: &std::path::Path, name: &str| -> Vec<u8> {
        let r = quant_core::st_io::reader::SafetensorsReader::open(p).unwrap();
        r.tensor_bytes(name).unwrap().to_vec()
    };
    let single_bias = read(&single, "blocks.1.bias");
    let sharded_bias = read(&sharded, "blocks.1.bias");
    assert_ne!(
        single_bias, sharded_bias,
        "cross-shard bias must differ: single mode corrects, sharded copies"
    );

    // The sharded-mode bias equals the ORIGINAL input bias (verbatim copy).
    let input_bias = read(&dir.join("input").join(SHARDS[1]), "blocks.1.bias");
    assert_eq!(sharded_bias, input_bias);

    // blocks.0.bias (same shard as its weight) is corrected in BOTH modes,
    // and identically so (per-shard quantization == union quantization for
    // tensors whose whole dependency set lives in one shard).
    let single_b0 = read(&single, "blocks.0.bias");
    let sharded_b0 = read(&dir.join("output_sharded").join(SHARDS[0]), "blocks.0.bias");
    assert_eq!(single_b0, sharded_b0);
}

#[test]
fn sharded_rerun_is_idempotent() {
    // Running sharded quantization twice into the same directory resumes
    // (everything already done) and leaves every byte unchanged.
    let dir = golden("sharded_model");
    let input = dir.join("input");
    let model = discover_shards(&input).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let out_dir = tmp.path().join("output_sharded");

    stream_quantize_sharded(&model, &out_dir, &ref_config()).unwrap();
    let before: Vec<(String, Vec<u8>)> = SHARDS
        .iter()
        .map(|s| (s.to_string(), std::fs::read(out_dir.join(s)).unwrap()))
        .collect();

    stream_quantize_sharded(&model, &out_dir, &ref_config()).unwrap();

    for (name, bytes) in &before {
        assert_eq!(
            &std::fs::read(out_dir.join(name)).unwrap(),
            bytes,
            "re-run must not alter {name}"
        );
    }
}
