//! IQ-family grid infrastructure — a port of llama.cpp's `iq2xs_init_impl`
//! / `iq3xs_init_impl` (docs/ref/llama.cpp, MIT) plus the packed lattice
//! tables (see `gguf_iq_tables_data`, generated by
//! `tools/extract_iq_tables.py` — the numbers are parsed straight from the
//! vendored C, never transcribed by hand).
//!
//! Upstream builds three structures per lattice at `ggml_quantize_init()`
//! time (ggml-quants.c:2852-3268 for iq2/iq1, :3703-3893 for iq3):
//!
//! **iq2/iq1 family** — 8 lanes of 2 bits:
//! 1. **grid** — each u16 packed point expanded to a u64 of 8 × i8 lanes
//!    `2*l + 1` (:3119-3126);
//! 2. **kmap** — 16-bit index (2 bits/lane) → grid row, `-1` if off the
//!    lattice (:3129-3142);
//! 3. **neighbours** — for every off-lattice index, the ≤ nwant nearest
//!    grid rows, `qsort`ed by squared distance with index tie-break,
//!    stored as `[count, idx...]` (:3143-3264). The kmap entry is
//!    `-(offset+1)` so the caller finds the list at
//!    `kneighbors - kmap[u] - 1` (:3237, :3389).
//!
//! **iq3 family** — 4 lanes of 3 bits (:3760ff):
//! 1. **grid** — u32 of 4 × i8 lanes `2*l + 1` (3-bit L, still odd quants);
//! 2. **kmap** — 12-bit index (3 bits/lane × 4), size 4096;
//! 3. **neighbours** — same scheme, `iq3_compare_func` (:3697) is the
//!    same d2-then-index order. nwant: grid 256 → 2, grid 512 → 3
//!    (:3761).
//!
//! Everything is built lazily once per format via `OnceLock` and shared by
//! reference; the build is deterministic, so the parity contract holds
//! across runs. Upstream's OpenMP passes are a perf split only — the
//! computation is sequentialized here without changing any output.

use std::sync::OnceLock;

pub(crate) use crate::gguf_iq_tables_data::{
    KGRID_1BIT_2048, KGRID_256, KGRID_2BIT_1024, KGRID_2BIT_256, KGRID_2BIT_512, KGRID_512,
    KVALUES_IQ4NL,
};

/// Which packed lattice + lane geometry a quantizer family uses.
///
/// Variants for the not-yet-ported quantizers (Iq2S/Iq1/Iq3Xxs/Iq3S —
/// Unsloth plan Phase 4.3 slices B/C) are exercised by the unit tests
/// below (kmap round-trip over every lattice) while no production
/// quantizer consumes them yet; that keeps the lattice builder itself
/// under test before the quantizer slices land.
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum IqLattice {
    /// iq2_xxs: kgrid_2bit_256, 2-bit lanes, nwant=2 neighbours.
    Iq2Xxs,
    /// iq2_xs: kgrid_2bit_512, 2-bit lanes, nwant=2.
    Iq2Xs,
    /// iq2_s: kgrid_2bit_1024, 2-bit lanes, nwant=1.
    Iq2S,
    /// iq1_s / iq1_m: kgrid_1bit_2048, 2-bit lanes, nwant=3.
    Iq1,
    /// iq3_xxs: kgrid_256, 3-bit lanes, nwant=2 (:3761).
    Iq3Xxs,
    /// iq3_s: kgrid_512, 3-bit lanes, nwant=3 (:3761).
    Iq3S,
}

impl IqLattice {
    fn packed_table(self) -> &'static [u16] {
        match self {
            IqLattice::Iq2Xxs => &KGRID_2BIT_256,
            IqLattice::Iq2Xs => &KGRID_2BIT_512,
            IqLattice::Iq2S => &KGRID_2BIT_1024,
            IqLattice::Iq1 => &KGRID_1BIT_2048,
            IqLattice::Iq3Xxs => &KGRID_256,
            IqLattice::Iq3S => &KGRID_512,
        }
    }

    /// Neighbour list band cap (`nwant`): iq2 :3110, iq3 :3761.
    fn nwant(self) -> usize {
        match self {
            IqLattice::Iq2Xxs | IqLattice::Iq2Xs => 2,
            IqLattice::Iq2S => 1,
            IqLattice::Iq1 => 3,
            IqLattice::Iq3Xxs => 2,
            IqLattice::Iq3S => 3,
        }
    }
}

/// The built structures for one lattice. The `grid`/`kmap`/`neighbours`
/// layouts differ per family — `wide` selects the 8-lane u64 form (iq2,
/// iq1) vs the 4-lane u32 form (iq3).
pub(crate) struct Lattice {
    /// true = 8 lanes × 2 bits in a u64 (iq2/iq1); false = 4 lanes ×
    /// 3 bits in a u32 (iq3).
    pub(crate) wide: bool,
    /// grid_size entries: each lane byte is `2*l + 1`.
    pub(crate) grid: Vec<u64>,
    /// Packed index → grid row, or `-(offset+1)` into neighbours.
    /// iq3 packs into the low 32 bits of each u64.
    pub(crate) kmap: Vec<i32>,
    /// Flat neighbour lists: `[count, idx..., count, idx...]`.
    pub(crate) neighbours: Vec<u16>,
}

impl Lattice {
    /// Expand a packed point to lanes of `2*l+1`.
    /// iq2 (:3122-3125): 8 lanes, `(k >> 2i) & 3`.
    /// iq3 (:3766-3770): 4 lanes, `(k >> 3i) & 7`, u32.
    fn expand_point(&self, k: u16) -> Vec<u8> {
        if self.wide {
            let mut v = vec![0u8; 8];
            for (i, b) in v.iter_mut().enumerate() {
                let l = ((k >> (2 * i as u16)) & 0x3) as i8;
                *b = (2 * l + 1) as u8;
            }
            v
        } else {
            let mut v = vec![0u8; 4];
            for (i, b) in v.iter_mut().enumerate() {
                let l = ((k >> (3 * i as u16)) & 0x7) as i8;
                *b = (2 * l + 1) as u8;
            }
            v
        }
    }

    /// Pack lane L values into the kmap index — mirrors the quantizer
    /// side. iq2: 8 lanes × 2 bits (:3138-3140, :3386). iq3: 4 lanes ×
    /// 3 bits (:3783-3785).
    pub(crate) fn pack_index(&self, l: &[i8]) -> u16 {
        if self.wide {
            let mut u: u16 = 0;
            for (i, &li) in l.iter().enumerate().take(8) {
                u |= ((li as u16) & 0x3) << (2 * i);
            }
            u
        } else {
            let mut u: u16 = 0;
            for (i, &li) in l.iter().enumerate().take(4) {
                u |= ((li as u16) & 0x7) << (3 * i);
            }
            u
        }
    }

    /// Lane values of a packed kmap index as grid-shaped bytes — used by
    /// the neighbour distance computation. iq2: lanes from bits 2i (:3171-
    /// 3173); iq3: from bits 3i (:3791-3793).
    pub(crate) fn index_lanes(&self, index: usize) -> Vec<i8> {
        if self.wide {
            (0..8)
                .map(|k| {
                    let l = ((index >> (2 * k)) & 0x3) as i8;
                    2 * l + 1
                })
                .collect()
        } else {
            (0..4)
                .map(|k| {
                    let l = ((index >> (3 * k)) & 0x7) as i8;
                    2 * l + 1
                })
                .collect()
        }
    }

    /// Neighbour list slice for kmap entry `gi` (negative). Returns the
    /// `[count, idx...]` slice — mirrors `kneighbors - kmap[u] - 1`
    /// (:3389).
    pub(crate) fn neighbours_of(&self, kmap_entry: i32) -> &[u16] {
        let off = (-kmap_entry - 1) as usize;
        let count = self.neighbours[off] as usize;
        &self.neighbours[off..off + 1 + count]
    }
}

/// Build one lattice: expand grid, build kmap, then the 3-pass neighbour
/// search (:3143-3264 / :3795-3893).
fn build(lattice: IqLattice) -> Lattice {
    let packed = lattice.packed_table();
    let grid_size = packed.len();
    let wide = !matches!(lattice, IqLattice::Iq3Xxs | IqLattice::Iq3S);
    let kmap_size = if wide { 1 << 16 } else { 1 << 12 };
    let proto = Lattice {
        wide,
        grid: Vec::new(),
        kmap: Vec::new(),
        neighbours: Vec::new(),
    };

    // grid: expand every packed point (:3119-3126 / :3765-3772).
    // Lane byte i of the u64 = `2*l_i + 1` (little-endian byte order).
    let mut grid = vec![0u64; grid_size];
    for (k, &pk) in packed.iter().enumerate() {
        let lanes = proto.expand_point(pk);
        let mut u: u64 = 0;
        for (i, &b) in lanes.iter().enumerate() {
            u |= (b as u64) << (8 * i);
        }
        grid[k] = u;
    }

    // kmap: each grid row's packed index → row; others -1 (:3129-3142 /
    // :3774-3787).
    let mut kmap = vec![-1i32; kmap_size];
    for (i, &g) in grid.iter().enumerate() {
        let bytes = g.to_le_bytes();
        let mut index: u16 = 0;
        if wide {
            for (k, b) in bytes.iter().enumerate().take(8) {
                let q = (b - 1) / 2;
                index |= (q as u16) << (2 * k);
            }
        } else {
            for (k, b) in bytes.iter().enumerate().take(4) {
                let q = (b - 1) / 2;
                index |= (q as u16) << (3 * k);
            }
        }
        kmap[index as usize] = i as i32;
    }

    let mut lat = Lattice {
        wide,
        grid,
        kmap,
        neighbours: Vec::new(),
    };

    // Pass 1: count neighbours per off-grid index (:3156-3196).
    let nwant = lattice.nwant();
    let mut n_per_i = vec![0i32; kmap_size];
    let mut num_neighbors = 0usize;
    let mut num_not_in_map = 0usize;
    let mut dist2: Vec<(i32, i32)> = vec![(0, 0); grid_size];
    for i in 0..kmap_size {
        if lat.kmap[i] >= 0 {
            continue;
        }
        num_not_in_map += 1;
        let pos = lat.index_lanes(i);
        for (j, &g) in lat.grid.iter().enumerate() {
            let pg = g.to_le_bytes();
            let mut d2 = 0i32;
            for (k, &p) in pos.iter().enumerate() {
                d2 += ((pg[k] as i8) - p) as i32 * ((pg[k] as i8) - p) as i32;
            }
            dist2[j] = (d2, j as i32);
        }
        // iq2_compare_func / iq3_compare_func: d2 then index (:2847, :3697).
        dist2.sort_unstable();
        let mut n = 0i32;
        let mut d2 = dist2[0].0;
        let mut nhave = 1usize;
        for j in 0..grid_size {
            if dist2[j].0 > d2 {
                if nhave == nwant {
                    break;
                }
                d2 = dist2[j].0;
                nhave += 1;
            }
            n += 1;
        }
        n_per_i[i] = n;
        num_neighbors += n as usize;
    }

    // Pass 2: offsets — prefix sums, +1 per list for the count slot
    // (:3201-3211 / :3857-3866).
    let mut neighbours = vec![0u16; num_neighbors + num_not_in_map];
    let mut offsets = vec![-1i32; kmap_size];
    let mut counter = 0usize;
    for i in 0..kmap_size {
        if lat.kmap[i] >= 0 {
            continue;
        }
        offsets[i] = counter as i32;
        counter += 1 + n_per_i[i] as usize;
    }

    // Pass 3: write the lists (:3224-3246 / :3873-3893).
    let kmap_copy = lat.kmap.clone();
    for i in 0..kmap_size {
        if kmap_copy[i] >= 0 {
            continue;
        }
        let pos = lat.index_lanes(i);
        for (j, &g) in lat.grid.iter().enumerate() {
            let pg = g.to_le_bytes();
            let mut d2 = 0i32;
            for (k, &p) in pos.iter().enumerate() {
                d2 += ((pg[k] as i8) - p) as i32 * ((pg[k] as i8) - p) as i32;
            }
            dist2[j] = (d2, j as i32);
        }
        dist2.sort_unstable();
        let local_counter = offsets[i] as usize;
        lat.kmap[i] = -(local_counter as i32 + 1);
        let start = local_counter;
        // Neighbour entries start right after the count slot; write them
        // in band order, stopping at the nwant-th distinct distance
        // (:3240-3245).
        let mut n = 0usize;
        let mut d2 = dist2[0].0;
        let mut nhave = 1usize;
        for (cur, &(dj, idx)) in dist2.iter().enumerate() {
            if dj > d2 {
                if nhave == nwant {
                    break;
                }
                d2 = dj;
                nhave += 1;
            }
            neighbours[start + 1 + cur] = idx as u16;
            n += 1;
        }
        neighbours[start] = n as u16;
    }

    Lattice {
        wide,
        grid: lat.grid,
        kmap: lat.kmap,
        neighbours,
    }
}

/// Shared per-format lattices (built once, deterministic).
pub(crate) fn lattice(kind: IqLattice) -> &'static Lattice {
    static IQ2XXS: OnceLock<Lattice> = OnceLock::new();
    static IQ2XS: OnceLock<Lattice> = OnceLock::new();
    static IQ2S: OnceLock<Lattice> = OnceLock::new();
    static IQ1: OnceLock<Lattice> = OnceLock::new();
    static IQ3XXS: OnceLock<Lattice> = OnceLock::new();
    static IQ3S: OnceLock<Lattice> = OnceLock::new();
    match kind {
        IqLattice::Iq2Xxs => IQ2XXS.get_or_init(|| build(kind)),
        IqLattice::Iq2Xs => IQ2XS.get_or_init(|| build(kind)),
        IqLattice::Iq2S => IQ2S.get_or_init(|| build(kind)),
        IqLattice::Iq1 => IQ1.get_or_init(|| build(kind)),
        IqLattice::Iq3Xxs => IQ3XXS.get_or_init(|| build(kind)),
        IqLattice::Iq3S => IQ3S.get_or_init(|| build(kind)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grid_expansion_matches_upstream_shape() {
        // First point of kgrid_2bit_256 is 0 → all lanes l=0 → 1 per byte
        // (:3123-3125).
        let lat = lattice(IqLattice::Iq2Xxs);
        assert_eq!(lat.grid[0], 0x0101010101010101u64);
        // Second entry 2: (2 >> 0) & 3 = 2 → lane0 l=2 → byte0 = 2*2+1
        // = 5; all other lanes l=0 → 1.
        assert_eq!(lat.grid[1].to_le_bytes()[0], 5);
        assert_eq!(lat.grid[1].to_le_bytes()[1], 1);
        // iq3: kgrid_256[0] = 0 → 4 lanes of 1.
        let lat3 = lattice(IqLattice::Iq3Xxs);
        assert_eq!(lat3.grid[0] & 0xffffffff, 0x01010101);
    }

    #[test]
    fn kmap_round_trips_every_grid_point() {
        // Every grid row's packed index must map back to itself
        // (:3134-3142 / :3774-3787 build exactly this invariant).
        for kind in [
            IqLattice::Iq2Xxs,
            IqLattice::Iq2Xs,
            IqLattice::Iq2S,
            IqLattice::Iq1,
            IqLattice::Iq3Xxs,
            IqLattice::Iq3S,
        ] {
            let lat = lattice(kind);
            let packed = kind.packed_table();
            for (i, &k) in packed.iter().enumerate() {
                let lanes = {
                    // decode exactly as the kmap build did
                    let bytes = lat.grid[i].to_le_bytes();
                    let n = if lat.wide { 8 } else { 4 };
                    let bits = if lat.wide { 2 } else { 3 };
                    let mut u: u16 = 0;
                    for b in 0..n {
                        let l = ((bytes[b] - 1) / 2) as u16;
                        u |= l << (bits * b);
                    }
                    u
                };
                let _ = k; // packed value itself unused after decode
                assert_eq!(
                    lat.kmap[lanes as usize], i as i32,
                    "{kind:?}: grid row {i} must round-trip its kmap index"
                );
            }
        }
    }

    #[test]
    fn neighbours_are_sorted_by_distance() {
        // For a sample off-grid index, the stored list must be in
        // nondecreasing squared distance (:3174-3192).
        let lat = lattice(IqLattice::Iq2Xxs);
        let grid_size = KGRID_2BIT_256.len();
        let mut probe = None;
        for i in 0..lat.kmap.len() {
            if lat.kmap[i] < 0 {
                probe = Some(i);
                break;
            }
        }
        let i = probe.expect("off-grid index exists");
        let list = lat.neighbours_of(lat.kmap[i]);
        assert!(*list.first().unwrap() > 0);
        let pos = lat.index_lanes(i);
        let dist = |j: usize| -> i32 {
            let pg = lat.grid[j].to_le_bytes();
            let mut d2 = 0i32;
            for (k, &p) in pos.iter().enumerate() {
                d2 += ((pg[k] as i8) - p) as i32 * ((pg[k] as i8) - p) as i32;
            }
            d2
        };
        let mut last = -1i32;
        for &j in &list[1..] {
            let j = j as usize;
            assert!(j < grid_size);
            let d = dist(j);
            assert!(d >= last, "neighbour list must be sorted");
            last = d;
        }
    }

    #[test]
    fn build_is_deterministic() {
        // Two fresh builds must agree bit-for-bit (no allocator or
        // iteration-order dependence).
        let a = build(IqLattice::Iq2Xxs);
        let b = build(IqLattice::Iq2Xxs);
        assert_eq!(a.grid, b.grid);
        assert_eq!(a.kmap, b.kmap);
        assert_eq!(a.neighbours, b.neighbours);
        let a = build(IqLattice::Iq3S);
        let b = build(IqLattice::Iq3S);
        assert_eq!(a.grid, b.grid);
        assert_eq!(a.kmap, b.kmap);
        assert_eq!(a.neighbours, b.neighbours);
    }

    #[test]
    fn iq3_kmap_size_is_4096() {
        let lat = lattice(IqLattice::Iq3Xxs);
        assert_eq!(lat.kmap.len(), 4096);
        let lat = lattice(IqLattice::Iq3S);
        assert_eq!(lat.kmap.len(), 4096);
    }
}
