//! Tier 2 S06 — reconstruction-error benchmark for the opt-in quality modes.
//!
//! MEASURES, DOES NOT GATE. The point of this bench is to make "is the quality
//! mode actually better?" a *measured, reproducible* question instead of an
//! assertion. It PRINTS a base-vs-quality table; it is not a pass/fail gate.
//! Benches do not run in `cargo test`, and turning a criterion bench into a
//! hard gate would be the wrong tool for a decision that needs review.
//!
//! # The metric
//!
//! ```text
//! rel_l2 = Σ (w − dequantize(quantize(w)))²  /  Σ w²
//! ```
//!
//! accumulated in **f64**, with the reconstruction produced by the SHIPPED
//! PUBLIC dequantizers -- [`dequantize_nvfp4`] and [`dequantize_mxfp8`].
//! There is deliberately no private reimplementation of the dequant math here:
//! a private copy could drift from the shipped one, and then this bench would
//! be measuring something the crate does not actually do at runtime. The
//! `w` in the numerator and denominator is the ORIGINAL fixture tensor, not
//! the bf16-rounded or zero-padded internal copy.
//!
//! # The pre-registered decision rule
//!
//! Fixed BEFORE any of these numbers were measured, reproduced verbatim in the
//! printed output so the verdict is mechanical rather than retrofitted:
//!
//! | Outcome                                          | Action                        |
//! |--------------------------------------------------|-------------------------------|
//! | improves rel_l2 on >=3 of 4 AND none regress >1% | SHIP                          |
//! | improves on <3 of 4                              | DO NOT SHIP                   |
//! | any distribution regresses by >1%                 | DO NOT SHIP                   |
//! | gain <2% aggregate                               | MARGINAL — keep, do not advertise |
//!
//! "improves" = ratio < 1.0. "regresses by >1%" = ratio > 1.01. "aggregate" =
//! the mean of the four per-distribution relative gains, `(1 − mean(ratio))`,
//! stated in the output so the arithmetic is not a black box.
//!
//! The unit of counting is the DISTRIBUTION, not the row. The fixture carries
//! four shapes per distribution, so counting rows would silently turn the "3
//! of 4" bar into "12 of 16" and make the rule four times easier to clear.
//! `per_distribution` collapses each format's rows to one mean ratio per
//! distribution before any of the rule is applied.
//!
//! # `int8_clip09` — the S07 arm, and why it is here
//!
//! The third row of the table is INT8 absmax clipping
//! ([`quantize_int8_weight_clipped`], `--format int8_clip09`): the quant scale
//! comes from `0.9 * row_max` rather than `row_max`, trading the top of the
//! range for finer steps below it.
//!
//! It is measured in **row** scaling, which is the mode the clip is defined in
//! terms of and the only one that covers the whole fixture (the block path
//! asserts divisibility, and two of the four shapes are prime in one or both
//! dimensions).
//!
//! The ratio is FIXED at [`INT8_CLIP_RATIO`] and is not a parameter here. A
//! sweep over clip ratios, evaluated until one of them cleared the bar, would
//! be a threshold fitted to this fixture rather than a measurement of the idea
//! — and this bench's whole purpose is to be the thing that cannot be tuned
//! into a pass.
//!
//! # MEASURED RESULT: DO NOT SHIP
//!
//! Recorded here so the verdict travels with the code that produced it:
//!
//! ```text
//! int8_clip09  aggregate gain -2.5e13%   worst regression 9.9e13%   improved 0/4
//! ```
//!
//! 0 of 4 distributions improved and every one regressed, so the rule fires
//! twice over (`<3 of 4` and `>1%` regression). This is not a marginal miss —
//! the mode is 31x-14000x worse than plain INT8. The mechanism is structural:
//! INT8's 127 levels leave almost no rounding error for a finer step to
//! recover, while the saturated tail's error is unbounded by the step. See
//! `tests/int8_clip09_negative_result.rs` for the full analysis, including an
//! independent analytic model that confirms the kernel is correct and the
//! regression is real.
//!
//! # Fixture
//!
//! `tests/fixtures/quality/{weights.f32,manifest.json}`, generated by
//! `tools/gen_quality_bench.py` and COMMITTED. Both `include_bytes!` paths
//! below point into `crates/`, never into `docs/` — `.gitignore:16` ignores
//! `docs/` wholesale, and a build input pointing at an ignored file breaks the
//! whole bench binary on a fresh clone. The manifest's SHA-256 is verified
//! against the blob at startup, so a silently-swapped or truncated fixture
//! fails loudly instead of reporting plausible-looking numbers.
//!
//! # A note on what is (and is not) timed
//!
//! The NVFP4 quality path is a search and is far more expensive than the
//! default path. Timing it inside the criterion loop would take minutes per
//! distribution and would measure search COST, which is not what this bench is
//! for. So the table is computed ONCE, up front and untimed, from the shipped
//! entry points; the timed portion below is the cheap dequantize + rel_l2
//! measurement, which is what actually recurs in a real pipeline. The printed
//! table is the deliverable; the criterion HTML report is a bonus.

use std::sync::OnceLock;

use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion, Throughput};
use quant_core::quant::{
    dequantize_int8, quantize_int8_weight, quantize_int8_weight_clipped, Int8QuantResult,
    ScalingMode as Int8ScalingMode, INT8_CLIP_RATIO,
};
use quant_core::quant_mxfp8::{
    dequantize_mxfp8, quantize_mxfp8_weight, quantize_mxfp8_weight_compensated, Mxfp8QuantResult,
};
use quant_core::quant_nvfp4::{
    dequantize_nvfp4, quantize_nvfp4_weight, quantize_nvfp4_weight_quality, Nvfp4QuantResult,
};

const BLOB: &[u8] = include_bytes!("../tests/fixtures/quality/weights.f32");
const MANIFEST: &str = include_str!("../tests/fixtures/quality/manifest.json");

/// Regressions beyond this are disqualifying under the pre-registered rule.
const REGRESSION_TOLERANCE: f64 = 1.01;
/// Below this aggregate gain the mode is MARGINAL even if it technically wins.
const MARGINAL_GAIN: f64 = 0.02;
/// A distribution must land under this ratio to count as "improved".
const IMPROVED_RATIO: f64 = 1.0;

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

/// One (distribution, shape) fixture case, materialized as f32.
struct Case {
    id: String,
    distribution: String,
    rows: usize,
    cols: usize,
    w: Vec<f32>,
}

impl Case {
    fn len(&self) -> usize {
        self.w.len()
    }
}

/// Minimal view of one manifest entry. Hand-parsed through `serde_json::Value`
/// rather than a `#[derive(Deserialize)]` struct: the manifest is a fixture
/// that a Python generator owns, and a struct here would be a second place for
/// its shape to drift.
fn load_cases() -> Vec<Case> {
    let v: serde_json::Value =
        serde_json::from_str(MANIFEST).expect("quality fixture manifest must be valid JSON");
    let cases = v["cases"]
        .as_array()
        .expect("manifest must carry a `cases` array");

    let mut out = Vec::with_capacity(cases.len());
    for c in cases {
        let offset = c["offset_elements"]
            .as_u64()
            .expect("offset_elements must be an integer") as usize;
        let length = c["length_elements"]
            .as_u64()
            .expect("length_elements must be an integer") as usize;

        let start = offset * 4;
        let end = start + length * 4;
        let bytes = BLOB.get(start..end).unwrap_or_else(|| {
            panic!(
                "fixture case {id} runs past the end of the blob",
                id = c["id"]
            )
        });

        let w: Vec<f32> = bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect();
        debug_assert_eq!(w.len(), length);

        out.push(Case {
            id: c["id"]
                .as_str()
                .expect("case id must be a string")
                .to_string(),
            distribution: c["distribution"]
                .as_str()
                .expect("distribution must be a string")
                .to_string(),
            rows: c["rows"].as_u64().expect("rows must be an integer") as usize,
            cols: c["cols"].as_u64().expect("cols must be an integer") as usize,
            w,
        });
    }
    out
}

/// Verify the blob against the SHA-256 the generator recorded.
///
/// Cheap insurance against the failure mode this whole fixture layout exists to
/// prevent: a bench that silently measures the wrong bytes and reports
/// confident nonsense. Uses the `sha2` dependency the crate already ships for
/// its parity fingerprint.
fn verify_blob_digest() {
    use sha2::{Digest, Sha256};

    let v: serde_json::Value =
        serde_json::from_str(MANIFEST).expect("quality fixture manifest must be valid JSON");
    let want = v["blob_sha256"]
        .as_str()
        .expect("manifest must carry a blob_sha256");
    let got = format!("{:x}", Sha256::digest(BLOB));
    assert_eq!(
        got, want,
        "quality fixture blob does not match the manifest SHA-256; \
         regenerate with `python tools/gen_quality_bench.py` (it is deterministic)"
    );
}

// ---------------------------------------------------------------------------
// The metric
// ---------------------------------------------------------------------------

/// `Σ (w − recon)² / Σ w²`, accumulated in f64.
///
/// The dequantizers return exactly `m * n` values already cropped back to the
/// unpadded shape, so `w` and `recon` are directly index-aligned — no stride
/// arithmetic and no masked tail here. That cropping is the shipped behaviour,
/// not an assumption of this bench.
fn rel_l2(w: &[f32], recon: &[f32]) -> f64 {
    assert_eq!(
        w.len(),
        recon.len(),
        "reconstruction must match the original tensor element-for-element"
    );
    let mut num = 0.0f64;
    let mut den = 0.0f64;
    for (&orig, &rec) in w.iter().zip(recon.iter()) {
        let o = f64::from(orig);
        let d = o - f64::from(rec);
        num += d * d;
        den += o * o;
    }
    num / den
}

// ---------------------------------------------------------------------------
// Table construction
// ---------------------------------------------------------------------------

/// Which format a row belongs to, and how to produce its base/quality pair.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Format {
    Nvfp4,
    Mxfp8,
    Int8Clip,
}

impl Format {
    fn name(self) -> &'static str {
        match self {
            Format::Nvfp4 => "nvfp4",
            Format::Mxfp8 => "mxfp8",
            Format::Int8Clip => "int8_clip09",
        }
    }

    /// `base` and `quality` reconstruction error for one tensor.
    ///
    /// Both arms go quantize -> SHIPPED dequantize. `quality` for MXFP8 is the
    /// proven no-op (measured at exactly 0.00% improvement, not shipped); it
    /// stays wired up so the negative result stays reproducible on demand —
    /// a benchmark that only ever runs the winner is not a benchmark.
    ///
    /// # Why INT8 is measured in ROW mode
    ///
    /// `int8_clip09` clips the per-row absmax, which is what
    /// `quantize_int8_weight_clipped` does in every scaling mode. ROW is the
    /// mode the clip is *defined* in terms of, and it is also the only mode
    /// that covers the whole fixture: the block path asserts divisibility by
    /// `block_size`, and `ragged_37x53` / `ragged_17x129` are prime in one or
    /// both dimensions, so a block-mode arm would panic on half the cases
    /// rather than measure them. The CLI preset is reachable in all three
    /// modes, but a partial-coverage INT8 row would be worse than an honest
    /// row-mode one.
    fn measure(self, w: &[f32], rows: usize, cols: usize) -> (f64, f64) {
        match self {
            Format::Nvfp4 => {
                let base = quantize_nvfp4_weight(w, rows, cols);
                let quality = quantize_nvfp4_weight_quality(w, rows, cols);
                (
                    rel_l2(w, &dequantize_nvfp4(&base, rows, cols)),
                    rel_l2(w, &dequantize_nvfp4(&quality, rows, cols)),
                )
            }
            Format::Mxfp8 => {
                let base = quantize_mxfp8_weight(w, rows, cols);
                let quality = quantize_mxfp8_weight_compensated(w, rows, cols);
                (
                    rel_l2(w, &dequantize_mxfp8(&base, rows, cols)),
                    rel_l2(w, &dequantize_mxfp8(&quality, rows, cols)),
                )
            }
            Format::Int8Clip => {
                // `block_size` is unused in Row mode; 128 keeps the value
                // canonical and matches the CLI default.
                let base = quantize_int8_weight(w, rows, cols, Int8ScalingMode::Row, 128);
                let quality = quantize_int8_weight_clipped(
                    w,
                    rows,
                    cols,
                    Int8ScalingMode::Row,
                    128,
                    INT8_CLIP_RATIO,
                );
                (
                    rel_l2(
                        w,
                        &dequantize_int8(
                            &base.qdata,
                            &base.scale,
                            rows,
                            cols,
                            Int8ScalingMode::Row,
                            128,
                        ),
                    ),
                    rel_l2(
                        w,
                        &dequantize_int8(
                            &quality.qdata,
                            &quality.scale,
                            rows,
                            cols,
                            Int8ScalingMode::Row,
                            128,
                        ),
                    ),
                )
            }
        }
    }
}

/// Every format the table reports on, in print order.
const FORMATS: [Format; 3] = [Format::Nvfp4, Format::Mxfp8, Format::Int8Clip];

struct Row {
    format: Format,
    distribution: String,
    shape: String,
    dims: String,
    base: f64,
    quality: f64,
    ratio: f64,
}

fn build_rows(cases: &[Case]) -> Vec<Row> {
    let mut rows = Vec::new();
    for format in FORMATS {
        for c in cases {
            let (base, quality) = format.measure(&c.w, c.rows, c.cols);
            rows.push(Row {
                format,
                distribution: c.distribution.clone(),
                shape: c.id.split('/').nth(1).unwrap_or("?").to_string(),
                dims: format!("{}x{}", c.rows, c.cols),
                base,
                quality,
                // A zero base error would make the ratio undefined; treat it as
                // "no measurable change" rather than NaN-poisoning the table.
                ratio: if base > 0.0 { quality / base } else { 1.0 },
            });
        }
    }
    rows
}

/// The pre-registered verdict for one format, evaluated mechanically.
struct Verdict {
    action: &'static str,
    improves: usize,
    total: usize,
    worst_regression: f64,
    aggregate_gain: f64,
    reasoning: String,
}

/// Collapse a format's rows to ONE ratio per distribution, in first-seen order.
///
/// The decision rule counts *distributions* ("improves on >=3 of 4"), and the
/// fixture carries four shapes per distribution. Counting shapes instead would
/// silently change the denominator from 4 to 16 and make the "3" bar four
/// times easier to clear — so the aggregation is done explicitly here rather
/// than left to whichever loop happens to run first. A distribution's ratio is
/// the mean of its shapes' ratios, which keeps the "aggregate gain" figure in
/// the printed table equal to the mean of the per-distribution gains.
fn per_distribution(rows: &[Row], format: Format) -> Vec<(String, f64)> {
    let mut order: Vec<String> = Vec::new();
    let mut sums: Vec<f64> = Vec::new();
    let mut counts: Vec<usize> = Vec::new();
    for r in rows.iter().filter(|r| r.format == format) {
        match order.iter().position(|d| *d == r.distribution) {
            Some(i) => {
                sums[i] += r.ratio;
                counts[i] += 1;
            }
            None => {
                order.push(r.distribution.clone());
                sums.push(r.ratio);
                counts.push(1);
            }
        }
    }
    order
        .into_iter()
        .zip(sums)
        .zip(counts)
        .map(|((d, s), c)| (d, s / c as f64))
        .collect()
}

fn evaluate(rows: &[Row], format: Format) -> Verdict {
    let dists = per_distribution(rows, format);
    let total = dists.len();
    let improves = dists.iter().filter(|(_, r)| *r < IMPROVED_RATIO).count();

    // Worst per-distribution regression, as a positive fraction (0.04 = 4% worse).
    let worst_regression = dists
        .iter()
        .map(|(_, r)| (r - 1.0).max(0.0))
        .fold(0.0f64, f64::max);
    // Aggregate gain = mean of the per-distribution relative gains.
    let mean_ratio = dists.iter().map(|(_, r)| *r).sum::<f64>() / total as f64;
    let aggregate_gain = 1.0 - mean_ratio;

    let regressed = worst_regression > REGRESSION_TOLERANCE - 1.0;

    // Order matters, and mirrors the rule table top to bottom: a disqualifying
    // regression outranks a win count, which outranks the magnitude check.
    let (action, reasoning) = if regressed {
        (
            "DO NOT SHIP",
            format!(
                "a distribution regressed by {:.2}% (> 1%)",
                worst_regression * 100.0
            ),
        )
    } else if improves < 3 {
        (
            "DO NOT SHIP",
            format!("improves on {improves} of {total} distributions (< 3)"),
        )
    } else if aggregate_gain < MARGINAL_GAIN {
        (
            "MARGINAL",
            format!(
                "clears the 3-of-4 bar but aggregate gain {:.2}% < 2%",
                aggregate_gain * 100.0
            ),
        )
    } else {
        (
            "SHIP",
            format!(
                "improves {improves}/{total}, worst regression {:.2}%, aggregate gain {:.2}%",
                worst_regression * 100.0,
                aggregate_gain * 100.0
            ),
        )
    };

    Verdict {
        action,
        improves,
        total,
        worst_regression,
        aggregate_gain,
        reasoning,
    }
}

fn print_table(rows: &[Row]) {
    println!();
    println!("Tier 2 quality modes — reconstruction error (rel_l2, lower is better)");
    println!(
        "metric: rel_l2 = sum((w - dequantize(quantize(w)))^2) / sum(w^2), \
         accumulated in f64"
    );
    println!("dequantizers: quant_core::quant_nvfp4::dequantize_nvfp4 / quant_mxfp8::dequantize_mxfp8 (shipped)");
    println!();

    println!(
        "{:<8} {:<13} {:<16} {:>13} {:>13} {:>10} {:>9}",
        "format", "distribution", "shape", "base", "quality", "ratio", "gain"
    );
    println!("{}", "-".repeat(88));
    for r in rows {
        println!(
            "{:<8} {:<13} {:<16} {:>13.6} {:>13.6} {:>10.6} {:>8.2}%",
            r.format.name(),
            r.distribution,
            format!("{} {}", r.shape, r.dims),
            r.base,
            r.quality,
            r.ratio,
            (1.0 - r.ratio) * 100.0
        );
    }
    println!();
    println!(
        "Per-distribution aggregate (mean of the 4 distribution ratios) and worst regression:"
    );
    for format in FORMATS {
        let v = evaluate(rows, format);
        println!(
            "  {:<12} aggregate gain {:>7.2}%   worst regression {:>6.2}%   improved {}/{}",
            format.name(),
            v.aggregate_gain * 100.0,
            v.worst_regression * 100.0,
            v.improves,
            v.total
        );
    }
    println!();

    println!("PRE-REGISTERED DECISION RULE (fixed before any measurement)");
    println!("  improves rel_l2 on >=3 of 4 AND none regresses by >1%  -> SHIP");
    println!("  improves on <3 of 4                                     -> DO NOT SHIP");
    println!("  any distribution regresses by >1%                        -> DO NOT SHIP");
    println!("  gain <2% aggregate                                      -> MARGINAL (keep, do not advertise)");
    println!();
    println!("VERDICT");
    for format in FORMATS {
        let v = evaluate(rows, format);
        println!("  {:<12} {:<12} — {}", format.name(), v.action, v.reasoning);
    }
    println!();
}

// ---------------------------------------------------------------------------
// The computed table, shared between the printout and the timed section
// ---------------------------------------------------------------------------

struct Table {
    cases: Vec<Case>,
    rows: Vec<Row>,
    /// Base results kept for the timed dequantize benchmark, indexed by
    /// (format, case) in the same order the rows were built.
    base_nvfp4: Vec<Nvfp4QuantResult>,
    base_mxfp8: Vec<Mxfp8QuantResult>,
    base_int8: Vec<Int8QuantResult>,
}

fn table() -> &'static Table {
    static TABLE: OnceLock<Table> = OnceLock::new();
    TABLE.get_or_init(|| {
        verify_blob_digest();
        let cases = load_cases();
        let rows = build_rows(&cases);

        // Re-quantize the base arm to keep a live result object for the timed
        // dequantize benchmark below. Cheap relative to the NVFP4 search.
        let mut base_nvfp4 = Vec::new();
        let mut base_mxfp8 = Vec::new();
        let mut base_int8 = Vec::new();
        for c in &cases {
            base_nvfp4.push(quantize_nvfp4_weight(&c.w, c.rows, c.cols));
            base_mxfp8.push(quantize_mxfp8_weight(&c.w, c.rows, c.cols));
            base_int8.push(quantize_int8_weight(
                &c.w,
                c.rows,
                c.cols,
                Int8ScalingMode::Row,
                128,
            ));
        }

        Table {
            cases,
            rows,
            base_nvfp4,
            base_mxfp8,
            base_int8,
        }
    })
}

fn quality_error(c: &mut Criterion) {
    let t = table();
    print_table(&t.rows);

    let mut group = c.benchmark_group("quality_error");
    // Small tensors: the dequantize + rel_l2 pass is microseconds, so keep the
    // sample count modest and the window short.
    group.sample_size(50);
    group.measurement_time(std::time::Duration::from_secs(5));

    for (i, case) in t.cases.iter().enumerate() {
        let elements = case.len() as u64;
        group.throughput(Throughput::Elements(elements));
        let id = case.id.clone();

        group.bench_with_input(BenchmarkId::new("nvfp4", &id), &(), |b, _| {
            b.iter(|| {
                let recon = dequantize_nvfp4(&t.base_nvfp4[i], case.rows, case.cols);
                rel_l2(&case.w, &recon)
            })
        });
        group.bench_with_input(BenchmarkId::new("mxfp8", &id), &(), |b, _| {
            b.iter(|| {
                let recon = dequantize_mxfp8(&t.base_mxfp8[i], case.rows, case.cols);
                rel_l2(&case.w, &recon)
            })
        });
        group.bench_with_input(BenchmarkId::new("int8_clip09", &id), &(), |b, _| {
            b.iter(|| {
                let q = &t.base_int8[i];
                let recon = dequantize_int8(
                    &q.qdata,
                    &q.scale,
                    case.rows,
                    case.cols,
                    Int8ScalingMode::Row,
                    128,
                );
                rel_l2(&case.w, &recon)
            })
        });
    }
    group.finish();
}

criterion_group!(benches, quality_error);
criterion_main!(benches);
