#!/usr/bin/env python3
"""Extract the IQ grid tables from the vendored ggml-quants.c and emit a
Rust module (gguf_iq_tables.rs).

The tables are parsed straight from the C source — no hand transcription,
so the numbers are exactly upstream's. Covers:
  - kgrid_2bit_256 / 512 / 1024 (iq2_xxs / iq2_xs / iq2_s)
  - kgrid_1bit_2048 (iq1_s / iq1_m, NGRID_IQ1S = 2048)
  - kgrid_256 / kgrid_512 (iq3_xxs / iq3_s, from iq3xs_init_impl)
  - kvalues_iq4nl (iq4_nl / iq4_xs)

The llama.cpp source tree is not vendored in this repo — point the
LLAMA_CPP_DIR environment variable at your local llama.cpp checkout
first (it reads ggml/src/ggml-quants.c and ggml/src/ggml-common.h
from there).

Usage: python tools/extract_iq_tables.py > crates/quant-core/src/gguf_iq_tables_data.rs
"""

import os
import re
import sys
from pathlib import Path

LLAMA_CPP_DIR = os.environ.get("LLAMA_CPP_DIR")
if not LLAMA_CPP_DIR:
    raise SystemExit("set LLAMA_CPP_DIR to your local llama.cpp checkout")
SRC = Path(LLAMA_CPP_DIR) / "ggml/src/ggml-quants.c"
COMMON = Path(LLAMA_CPP_DIR) / "ggml/src/ggml-common.h"


def extract_array(text: str, name: str) -> list[int]:
    # static const uint16_t kgrid_2bit_256[256] = { ... };
    m = re.search(
        r"static const uint\d+_t\s+" + re.escape(name) + r"\[\w*\]\s*=\s*\{(.*?)\};",
        text,
        re.S,
    )
    if not m:
        raise SystemExit(f"table {name} not found")
    body = m.group(1)
    vals = [int(tok) for tok in re.findall(r"-?\d+", body)]
    return vals


def extract_iq4nl(text: str) -> list[int]:
    m = re.search(
        r"GGML_TABLE_BEGIN\(int8_t, kvalues_iq4nl, 16\)(.*?)GGML_TABLE_END",
        text,
        re.S,
    )
    if not m:
        raise SystemExit("kvalues_iq4nl not found")
    return [int(tok) for tok in re.findall(r"-?\d+", m.group(1))]


def emit(name: str, vals: list[int], ty: str, doc: str) -> None:
    print(f"/// {doc}")
    print(f"pub static {name}: [{ty}; {len(vals)}] = [")
    for i in range(0, len(vals), 16):
        row = ", ".join(f"{v:>6}" for v in vals[i : i + 16])
        print(f"    {row},")
    print("];")
    print()


def main() -> None:
    c_src = SRC.read_text(encoding="utf-8")
    c_common = COMMON.read_text(encoding="utf-8")

    print("// Generated by tools/extract_iq_tables.py — DO NOT EDIT by hand.")
    print("// Source: llama.cpp ggml-quants.c + ggml-common.h")
    print("// (MIT; the vendored upstream tree). Regenerate with the script, never patch")
    print("// values inline — parity with llama.cpp depends on these exact")
    print("// numbers.")
    print()

    emit(
        "KGRID_2BIT_256",
        extract_array(c_src, "kgrid_2bit_256"),
        "u16",
        "iq2_xxs lattice — 256 packed points (2 bits/lane, 8 lanes) :2859.",
    )
    emit(
        "KGRID_2BIT_512",
        extract_array(c_src, "kgrid_2bit_512"),
        "u16",
        "iq2_xs lattice — 512 packed points :2877.",
    )
    emit(
        "KGRID_1BIT_2048",
        extract_array(c_src, "kgrid_1bit_2048"),
        "u16",
        "iq1_s/iq1_m lattice — NGRID_IQ1S = 2048 points :2911.",
    )
    emit(
        "KGRID_2BIT_1024",
        extract_array(c_src, "kgrid_2bit_1024"),
        "u16",
        "iq2_s lattice — 1024 packed points :3041.",
    )
    emit(
        "KGRID_256",
        extract_array(c_src, "kgrid_256"),
        "u16",
        "iq3_xxs lattice — 256 packed points (3 bits/lane) iq3xs_init_impl :3706.",
    )
    emit(
        "KGRID_512",
        extract_array(c_src, "kgrid_512"),
        "u16",
        "iq3_s lattice — 512 packed points :3752 (second table in iq3xs_init_impl).",
    )
    emit(
        "KVALUES_IQ4NL",
        extract_iq4nl(c_common),
        "i8",
        "iq4_nl / iq4_xs 16-value non-linear dequant table (ggml-common.h :1120).",
    )

    # sanity: expected sizes
    for nm, expect in [
        ("KGRID_2BIT_256", 256),
        ("KGRID_2BIT_512", 512),
        ("KGRID_1BIT_2048", 2048),
        ("KGRID_2BIT_1024", 1024),
        ("KGRID_256", 256),
        ("KGRID_512", 512),
        ("KVALUES_IQ4NL", 16),
    ]:
        print(f"// {nm}: expected {expect} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
